# Generated by Django 3.2.3 on 2021-05-28 12:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('run_time', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('sample_video', models.FileField(upload_to='videos/')),
                ('finish_date', models.DateField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('Requirments', tinymce.models.HTMLField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.myprofile')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
    ]
