# Generated by Django 3.2.3 on 2021-05-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='run_time',
            field=models.CharField(choices=[('5 min', '5 min'), ('10 min', '10 min'), ('15 min', '15 min'), ('20 min', '20 min'), ('30 min', '30 min')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.CharField(choices=[('vedio_editing', 'vedio_editing'), ('Post-production', 'post-production')], max_length=100),
        ),
    ]
