# Generated by Django 3.2.3 on 2021-06-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_orders_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='pic',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sample_video',
            field=models.FileField(upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
