# Generated by Django 3.2.3 on 2021-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20210604_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
